Mathviews
HuyLafa/codeu_project_2017 pull request #5
Opened 2017-03-30 18:21 UTC by HuyLafa

Add a front-end chat view with math formula and Wolframalpha suport.

2017-03-30 18:49 UTC, fatlotus requested changes
The jQuery seems a little tricky -- is there a way to do it without dynamic CSS selectors?

2017-03-30 18:49 UTC, fatlotus commented on app/views/chat.scala.html
> +
format?

2017-03-30 18:49 UTC, fatlotus commented on app/views/chat.scala.html
> +<script type="text/javascript">
?

2017-03-30 18:49 UTC, fatlotus commented on app/views/chat.scala.html
> +    <div class="container" style="width: 100%; padding: 0;">
remove inline style?

2017-03-30 18:49 UTC, fatlotus commented on app/views/chat.scala.html
> +            <div class="col-sm-3 chat_sidebar">
dashes instead of underscores

2017-03-30 18:49 UTC, fatlotus commented on app/views/chat.scala.html
> +                            <input type="text" class="  search-query form-control" placeholder="Conversation"/>
whitespace

2017-03-30 18:49 UTC, fatlotus commented on app/views/chat.scala.html
> +                                <span class=" glyphicon glyphicon-search"></span>
whitespace

2017-03-30 18:49 UTC, fatlotus commented on app/views/chat.scala.html
> +                     <img src="https://avatars0.githubusercontent.com/u/9096489?v=3&s=460" alt="User Avatar"
nit: &amp;

2017-03-30 18:49 UTC, fatlotus commented on app/views/chat.scala.html
> +                     <span class="chat-img pull-left">
reindent

2017-03-30 18:49 UTC, fatlotus commented on public/javascripts/math_input.js
> +function setupMathInput() {
var setupMathInput = function() {

2017-03-30 18:49 UTC, fatlotus commented on public/javascripts/math_input.js
> +    if ( mathField ) {
if (foobar) {

also below

2017-03-30 18:49 UTC, fatlotus commented on public/javascripts/math_input.js
> +function openKeyboard() {
reformat

2017-03-30 18:49 UTC, fatlotus commented on app/views/chat.scala.html
> +* Source: http://bootsnipp.com/user/snippets/GQP0E
can't sign in

2017-03-30 18:49 UTC, fatlotus commented
This would be a lot of work, but it might be interesting to add Selenium tests or something for the client-side logic.

2017-03-30 18:51 UTC, HuyLafa commented on app/views/chat.scala.html
> +* Source: http://bootsnipp.com/user/snippets/GQP0E
This is just a plain view; we're not linking it with any back-end yet.

2017-03-30 19:00 UTC, fatlotus commented on public/javascripts/math_input.js
> +	}
} else {

2017-04-04 13:27 UTC, fatlotus requested changes
Almost there! :) LGTM, modulo some nits.

2017-04-04 13:27 UTC, fatlotus commented on app/views/chat.scala.html
> +* Source: http://bootsnipp.com/user/snippets/GQP0E
oh, no -- i meant the snippet! Maybe copy to gist or something?

2017-04-04 13:27 UTC, fatlotus commented on public/javascripts/math-input.js
> +//  $('#keyboard .keypad:not(.default)').hide();
If possible, strip out commented code from the CL -- we already have full history in Git.

2017-04-04 13:27 UTC, fatlotus commented on public/javascripts/math-input.js
> +      }
} else {

2017-04-04 13:27 UTC, fatlotus commented on public/javascripts/math-input.js
> +        mathField.keystroke('Left');
indent?

2017-04-04 13:27 UTC, fatlotus commented on public/javascripts/math-input.js
> +	$('#keyboard-wrapper').slideDown();
Please use either tabs or spaces (throughout the file)

(Might be possible to auto-format in your editor)

2017-04-05 13:30 UTC, fatlotus approved these changes

2017-04-05 13:30 UTC, merged